 {
  "build": {
    "merge-install": true,
    "cmake-args": [
      "-GNinja",
      "--no-warn-unused-cli",
      "-DCMAKE_BUILD_TYPE=RelWithDebInfo",
      "-DBUILD_DOCS:bool=false",
      "-DSKIP_optix:bool=true"
    ],
    "event-handlers": [
      "console_cohesion+",
      "console_package_list+",
    ]
  },
  "test": {
    "merge-install": true,
    "event-handlers": [
      "console_direct+",
    ]
  }
}
